services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nlp_app
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./cache/query/redis.conf:/usr/local/etc/redis/redis.conf
      - ./cache/query/data:/usr/local/etc/redis/data
